# Generated by Django 3.1.7 on 2021-03-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxcalculate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govt',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxcalculate.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
